=== ArtsiomT/EpamOOPtask/input/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
        <schema xmlns="http://www.w3.org/2001/XMLSchema"
                targetNamespace="http://www.example.com/tariffs"
                xmlns:tns="http://www.example.com/tariffs"
                elementFormDefault="qualified">
                <element name="tariffs">
                    <complexType>
                        <sequence>
                            <element ref="tns:tariff" minOccurs="1" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
               <element name="tariff" type="tns:Tariff" abstract="true"/>
                <element name="talk-tariff" type="tns:TalkTariff" substitutionGroup="tns:tariff"/>
                <element name="internet-tariff" type="tns:InternetTariff" substitutionGroup="tns:tariff"/>
                <element name="business-tariff" type="tns:BusinessTariff" substitutionGroup="tns:talk-tariff"/>
                <complexType name="Tariff" abstract="true">
                    <sequence>
                        <element name="license-fee" type="positiveInteger"/>
                        <element name="people-used" type="positiveInteger"/>
                    </sequence>
                    <attribute name="name" type="tns:Name" use="required"/>
                </complexType>
                <complexType name="TalkTariff" abstract="false">
                    <complexContent>
                        <extension base="tns:Tariff">
                            <sequence>
                                <element name="free-minutes" type="positiveInteger"/>
                                <element name="talk-cost" type="positiveInteger"/>
                                <element name="sms-cost" type="positiveInteger" />
                            </sequence>
                        </extension>
                    </complexContent>
                </complexType>
                <complexType name="InternetTariff" abstract="false">
                    <complexContent>
                        <extension base="tns:Tariff">
                            <sequence>
                                <element name="free-traffik" type="positiveInteger" />
                                <element name="megabyte-cost" type="positiveInteger"/>
                            </sequence>
                        </extension>
                    </complexContent>
                </complexType>
                <complexType name="BusinessTariff">
                    <complexContent>
                        <extension base="tns:TalkTariff">
                            <sequence>
                                 <element name="free-traffik" type="positiveInteger" />
                                 <element name="megabyte-cost" type="positiveInteger"/>
                            </sequence>
                        </extension>
                    </complexContent>
                </complexType>

        <simpleType name="Name">
            <restriction base="ID">
                   <pattern value="[а-яА-ЯёЁa-zA-Z0-9]{1,15}" />
            </restriction>
        </simpleType>
        </schema>

=== ArtsiomT/EpamOOPtask/input/tariffs-ext.xml
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/tariffs"
         xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">

        <talk-tariff name="Всеговорят">
            <license-fee>37700</license-fee>
            <people-used>56000</people-used>
            <free-minutes>100</free-minutes>
            <talk-cost>399</talk-cost>
            <sms-cost>350</sms-cost>
        </talk-tariff>
        <internet-tariff name="Пакет1500">
            <license-fee>69900</license-fee>
            <people-used>75000</people-used>
            <free-traffik>1500</free-traffik>
            <megabyte-cost>288</megabyte-cost>
        </internet-tariff>
        <business-tariff name="Smart1">
            <license-fee>109900</license-fee>
            <people-used>250000</people-used>
            <free-minutes>200</free-minutes>
            <talk-cost>365</talk-cost>
            <sms-cost>350</sms-cost>
            <free-traffik>1024</free-traffik>
            <megabyte-cost>30</megabyte-cost>
        </business-tariff>
        <talk-tariff name="Всеtojeговорят">
        <license-fee>37700</license-fee>
        <people-used>56000</people-used>
        <free-minutes>100</free-minutes>
        <talk-cost>399</talk-cost>
        <sms-cost>350</sms-cost>
        </talk-tariff>
</tariffs>
